version: '3'

services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "${KAFKA_PORT}:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME:      ${KAFKA_ADDRESS}
      KAFKA_ADVERTISED_PORT:           ${KAFKA_PORT}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS:             "${KAFKA_TOPIC}:1:1"
      KAFKA_ZOOKEEPER_CONNECT:         "zookeeper:2181"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
